-- sb_standard_control 테이블 MySQL INSERT 쿼리
-- 생성일시: 2025-12-31 17:05:42
-- 총 32개 레코드

-- 기존 데이터 삭제 (필요시 주석 해제)
-- DELETE FROM sb_standard_control;

INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (1, 'APD', 'APD01', 'Application 신규 권한 승인', '신규 권한이 필요한 경우 적절한 승인권자의 승인을 득한 후 권한을 부여합니다!', NULL, NULL, '계정명', '권한명', '권한시작일', 'SR번호', '요청자', '요청일자', '승인자', '승인일자', NULL, NULL, 3);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (2, 'APD', 'APD02', 'Application 부서이동자 권한 회수', '부서이동자의 기존 권한은 즉시 회수됩니다', NULL, NULL, '계정명', '부서이동일자', '권한회수 여부', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (3, 'APD', 'APD03', 'Application 퇴사자 접근 권한 회수', '퇴사자의 접근권한은 즉시 회수됩니다', NULL, NULL, '계정명', '퇴사일자', '권한회수 여부', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (4, 'APD', 'APD04', 'Application 관리자 권한 제한', '관리자 권한은 적절한 담당자로 제한됩니다', NULL, NULL, '관리자계정', '사용자명', '직무', '권한보유 사유', NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (5, 'APD', 'APD05', 'Application 권한 Monitoring', '전체 사용자의 모든 권한에 대한 적정성 모니터링이 수행됩니다', NULL, NULL, '기간', '모니터링 적정성 여부', '승인자', '승인일자', NULL, NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (6, 'APD', 'APD06', 'Application 패스워드', '패스워드는 기준에 따라 적절히 설정됩니다', NULL, NULL, '최소자리', '복잡성', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (7, 'APD', 'APD07', 'Data 직접변경 승인', '데이터 변경 필요시 적절한 승인권자의 승인을 득한 후 변경을 수행합니다', NULL, NULL, '데이터 변경', '변경일자', 'SR번호', '요청자', '요청일자', '승인자', '승인일자', NULL, NULL, NULL, 1);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (8, 'APD', 'APD08', 'Data 직접변경 권한 제한', '데이터 변경 권한은 적절한 담당자로 제한됩니다', NULL, NULL, '데이터 변경 계정', '사용자', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (9, 'APD', 'APD09', 'DB 접근권한 승인', 'DB 접근권한이 필요한 경우 적절한 승인권자의 승인을 득한 후 권한을 부여합니다', NULL, NULL, 'DB접근권한', '권한부여일자', 'SR번호', '요청자', '요청일자', '승인자', '승인일자', NULL, NULL, NULL, 2);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (10, 'APD', 'APD10', 'DB 관리자 권한 제한', 'DB 관리자 권한은 적절한 담당자로 제한됩니다', NULL, NULL, '관리자계정', '사용자', '직무', '권한보유 사유', NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (11, 'APD', 'APD11', 'DB 패스워드', '패스워드는 기준에 따라 적절히 설정됩니다', NULL, NULL, '최소자리', '복잡성', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (12, 'APD', 'APD12', 'OS 접근권한 승인', 'OS 접근권한이 필요한 경우 적절한 승인권자의 승인을 득한 후 권한을 부여합니다', NULL, NULL, 'OS접근권한', '권한부여일', 'SR번호', '요청자', '요청일자', '승인자', '승인일자', NULL, NULL, NULL, 2);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (13, 'APD', 'APD13', 'OS 관리자 권한 제한', 'OS 관리자 권한은 적절한 담당자로 제한됩니다', NULL, NULL, '관리자계정', '사용자', '직책', '권한보유 사유', NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (14, 'APD', 'APD14', 'OS 패스워드', '패스워드는 기준에 따라 적절히 설정됩니다', NULL, NULL, '최소자리', '복잡성', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (15, 'PC', 'PC01', '프로그램 변경 승인', '프로그램 변경이 필요한 경우 적절한 승인권자의 승인을 득한 후 변경을 수행합니다', NULL, NULL, '배포내용', '배포일자', 'SR번호', '요청자', '요청일자', '승인자', '승인일자자', NULL, NULL, NULL, 2);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (16, 'PC', 'PC02', '프로그램 변경 사용자 테스트', '프로그램 변경이 완료된 후 요청자에 의해 사용자 테스트가 수행됩니다', NULL, NULL, '배포내용', '배포일자', 'SR번호', '사용자 테스트 유무', '테스트 담당자', NULL, NULL, NULL, NULL, NULL, 2);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (17, 'PC', 'PC03', '프로그램 이관 승인', '프로그램 변경 완료 후 이관을 요청하고 적절한 승인권의 승인을 득한 후 이관을 수행합니다', NULL, NULL, '배포내용', '배포일자', 'SR번호', '요청자', '요청일자', '승인자', '승인일자', NULL, NULL, NULL, 2);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (18, 'PC', 'PC04', '이관담당자 권한 제한', '이관권한은 적절한 담당자로 제한되며 개발담당자와 분리됩니다', NULL, NULL, '이관권한', '사용자', '직책', '권한보유 사유', NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (20, 'PC', 'PC05', '개발/운영 환경 분리', '개발환경과 운영환경은 분리되어 운용됩니다', NULL, NULL, '운영환경', '개발환경', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (19, 'PC', 'PC06', '인프라 설정 변경', '인프라 설정 변경이 필요한 경우 적절한 승인권자의 승인을 득한 후 변경을 수행합니다', NULL, NULL, '설정변경 내용', '설정변경 일자', 'SR번호', '요청자', '요청일자', '승인자', '승인일자', NULL, NULL, NULL, 2);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (21, 'CO', 'CO01', '배치잡 스케줄 등록 승인', '스케줄 작업이 필요한 경우 적절한 승인권자의 승인을 득한 후 등록합니다', NULL, NULL, '배치잡 스케줄', '배치잡 스케줄 등록일자', 'SR번호', '요청자', '요청일자', '승인자', '승인일자', NULL, NULL, NULL, 2);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (22, 'CO', 'CO02', '배치잡 스케줄 등록 권한 제한', '스케줄 등록 권한은 적절한 담당자로 제한됩니다', NULL, NULL, '배치 스케줄 등록권한', '사용자', '직책', '권한보유 사유', NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (23, 'CO', 'CO03', '배치잡 Monitoring', '스케줄은 모니터링되어 오류 등을 적시에 조치합니다', NULL, NULL, '기간', '모니터링 적정성 여부', '승인자', '승인일자', NULL, NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (24, 'CO', 'CO04', '장애처리', '10', NULL, NULL, '장애내용', '장애일자', '문서번호', '조치내용', '승인자', '승인일자', NULL, NULL, NULL, NULL, 2);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (25, 'CO', 'CO05', '백업관리', NULL, NULL, NULL, '기간', '문서번호', '승인자', '승인일자', NULL, NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (26, 'CO', 'CO06', '데이터 센터 접근제한', NULL, NULL, NULL, '출입일자', '요청자', '요청일자', '승인자', '승인일자', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (27, 'PD', 'PD01', '타당성 검토 및 승인', NULL, NULL, NULL, '시스템 구축 내용', '구축 완료 일자', '타당성 검토 여부', '승인자', '승인일자', NULL, NULL, NULL, NULL, NULL, 2);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (28, 'PD', 'PD02', '요구사항 정의서 작성 및 검토', NULL, NULL, NULL, '시스템 구축 내용', '구축 완료 일자', '요구사항 정의서 작성 여부', '승인자', '승인일자자', NULL, NULL, NULL, NULL, NULL, 2);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (29, 'PD', 'PD03', '단위 테스트 및 통합 테스트 진행', NULL, NULL, NULL, '시스템 구축 내용', '구축 완료 일자', '테스트 여부', '승인자', '승인일자', NULL, NULL, NULL, NULL, NULL, 2);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (30, 'PD', 'PD04', '데이터 이관 계획서 작성 및 검토', NULL, NULL, NULL, '시스템 구축 내용', '구축 완료 일자', '데이터 이관 계획 여부', '승인자', '승인일자', NULL, NULL, NULL, NULL, NULL, 2);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (31, 'PD', 'PD05', '사용자 교육', NULL, NULL, NULL, '시스템 구축 내용', '구축 완료 일자', '사용자 교육 여부', '승인자', '승인일자', NULL, NULL, NULL, NULL, NULL, 2);
INSERT INTO sb_standard_control (std_control_id, control_category, control_code, control_name, control_description, ai_review_prompt, creation_date, attribute0, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, population_attribute_count) VALUES (32, 'PD', 'PD06', '검수보고서 승인', NULL, NULL, NULL, '시스템 구축 내용', '구축 완료 일자', '검수보고서 작성 여부', '승인자', '승인일자', NULL, NULL, NULL, NULL, NULL, 2);
